### ISSUE TITLE
Create OGP

### ISSUE THREAD

**Issue by re-taro** [re-taro/alibum#30]

**Comment by nekoshark02** [comment]
![add assets_ogp png and make og tsx by nekoshark02 · Pull Request #56 · re-taro_alibum - Vivaldi 2022_12_11 22_22_05](https://user-images.githubusercontent.com/82247089/206906187-9ab720aa-d88b-4e5c-a338-ee927284effd.png)

これの直し方教えてください！直し方わかりません...

**Comment by re-taro** [comment]
package managerがnpmだからです。yarnを使ってください
